version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.19.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.35
    - 14.14.36
  - dependency-name: "@types/react"
    versions:
    - 17.0.3
  - dependency-name: polished
    versions:
    - 4.1.1
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.3
  - dependency-name: styled-components
    versions:
    - 5.2.1
  - dependency-name: react-dom
    versions:
    - 17.0.2
  - dependency-name: react
    versions:
    - 16.14.0
    - 17.0.2
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.0
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: "@types/react-router-dom"
    versions:
    - 5.1.7
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.5
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 2.34.0
  - dependency-name: eslint-config-prettier
    versions:
    - 6.15.0
